# Generated by Django 6.0 on 2025-12-15 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ri', models.FloatField(help_text='R_i (seconds)')),
                ('ri_next', models.FloatField(help_text='R_i+1 (seconds)')),
                ('foot_j', models.FloatField(help_text='foot_j (seconds)')),
                ('r_j', models.FloatField(help_text='R_j (seconds)')),
                ('h', models.FloatField(help_text='h (meters)')),
                ('hr', models.FloatField(blank=True, help_text='Heart Rate (bpm)', null=True)),
                ('ptt', models.FloatField(blank=True, help_text='Pulse Transit Time (seconds)', null=True)),
                ('mbp', models.FloatField(blank=True, help_text='Mean Blood Pressure (mmHg)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, help_text='Optional file name reference', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
